### ISSUE TITLE
php兼容问题

### ISSUE THREAD

**Issue by gouchaoer** [slince/phpdish#5]
php7.0在执行php bin/console phpdish:install弹：
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Return value of ProxyManager\Configuration::setGeneratorStrategy() must be an instance of ProxyManager\void, none returned in /app/vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php:124
Stack trace:
#0 /app/vendor/symfony/symfony/src/Symfony/Bridge/ProxyManager/LazyProxy/Instantiator/RuntimeInstantiator.php(37): ProxyManager\Configuration->setGeneratorStrategy(Object(ProxyManager\GeneratorStrategy\EvaluatingGeneratorStrategy))
#1 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(731): Symfony\Bridge\ProxyManager\LazyProxy\Instantiator\RuntimeInstantiator->__construct()
#2 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(679): Symfony\Component\HttpKernel\Kernel->getContainerBuilder()
#3 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(572): Symfony\Component\HttpKernel\Kernel->buildContainer()
#4 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKern in /app/vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php on line 124
```

跑去看发现那个包这样写的：
```
public function setGeneratorStrategy(GeneratorStrategyInterface $generatorStrategy) : void
    {
        $this->generatorStrategy = $generatorStrategy;
    }
```
这是7.1的新特性，别说5.6了，7.0都不行

**Comment by slince** [comment]
```bash
composer show symfony/symfony 
```
你执行下上面命令看下symfony版本

**Comment by gouchaoer** [comment]
php7.0测试：
```
php -v
PHP 7.0.22 (cli) (built: Aug  9 2017 18:23:24) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
# cat p.php
<?php
function f():void
{
echo "f";
}

f();
# php p.php
fPHP Fatal error:  Uncaught TypeError: Return value of f() must be an instance of void, none returned in /home/gou_chao/p.php:5
Stack trace:
#0 /home/gou_chao/p.php(7): f()
#1 {main}
  thrown in /home/gou_chao/p.php on line 5

```
也就是说他兼容5.6，不兼容7.0吧

**Comment by gouchaoer** [comment]
```
 php70 composer.phar show symfony/symfony
name     : symfony/symfony
descrip. : The Symfony PHP framework
keywords : framework
versions : * v3.3.14
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/symfony/symfony.git 8e2b473de636a65a018b370d5e88778a260f0e33
dist     : [zip] https://api.github.com/repos/symfony/symfony/zipball/8e2b473de636a65a018b370d5e88778a260f0e33 8e2b473de636a65a018b370d5e88778a260f0e33
names    : symfony/symfony, psr/cache-implementation, psr/container-implementation, psr/simple-cache-implementation, symfony/asset, symfony/browser-kit, symfony/cache, symfony/class-loader, symfony/config, symfony/console, symfony/css-selector, symfony/debug, symfony/debug-bundle, symfony/dependency-injection, symfony/doctrine-bridge, symfony/dom-crawler, symfony/dotenv, symfony/event-dispatcher, symfony/expression-language, symfony/filesystem, symfony/finder, symfony/form, symfony/framework-bundle, symfony/http-foundation, symfony/http-kernel, symfony/inflector, symfony/intl, symfony/ldap, symfony/monolog-bridge, symfony/options-resolver, symfony/process, symfony/property-access, symfony/property-info, symfony/proxy-manager-bridge, symfony/routing, symfony/security, symfony/security-bundle, symfony/security-core, symfony/security-csrf, symfony/security-guard, symfony/security-http, symfony/serializer, symfony/stopwatch, symfony/templating, symfony/translation, symfony/twig-bridge, symfony/twig-bundle, symfony/validator, symfony/var-dumper, symfony/web-link, symfony/web-profiler-bundle, symfony/web-server-bundle, symfony/workflow, symfony/yaml

autoload
psr-4
Symfony\Bridge\Doctrine\ => src/Symfony/Bridge/Doctrine/
Symfony\Bridge\Monolog\ => src/Symfony/Bridge/Monolog/
Symfony\Bridge\ProxyManager\ => src/Symfony/Bridge/ProxyManager/
Symfony\Bridge\Twig\ => src/Symfony/Bridge/Twig/
Symfony\Bundle\ => src/Symfony/Bundle/
Symfony\Component\ => src/Symfony/Component/
classmap
src/Symfony/Component/Intl/Resources/stubs
exclude-from-classmap

requires
doctrine/common ~2.4
ext-xml *
fig/link-util ^1.0
php ^5.5.9|>=7.0.8
psr/cache ~1.0
psr/container ^1.0
psr/link ^1.0
psr/log ~1.0
psr/simple-cache ^1.0
symfony/polyfill-apcu ~1.1
symfony/polyfill-intl-icu ~1.0
symfony/polyfill-mbstring ~1.0
symfony/polyfill-php56 ~1.0
symfony/polyfill-php70 ~1.0
symfony/polyfill-util ~1.0
twig/twig ~1.34|~2.4

requires (dev)
cache/integration-tests dev-master
doctrine/annotations ~1.0
doctrine/cache ~1.6
doctrine/data-fixtures 1.0.*
doctrine/dbal ~2.4
doctrine/doctrine-bundle ~1.4
doctrine/orm ~2.4,>=2.4.5
egulias/email-validator ~1.2,>=1.2.8|~2.0
monolog/monolog ~1.11
ocramius/proxy-manager ~0.4|~1.0|~2.0
phpdocumentor/reflection-docblock ^3.0|^4.0
predis/predis ~1.0
sensio/framework-extra-bundle ^3.0.2
symfony/phpunit-bridge ~3.4|~4.0
symfony/security-acl ~2.8|~3.0

provides
psr/cache-implementation 1.0
psr/container-implementation 1.0
psr/simple-cache-implementation 1.0

conflicts
phpdocumentor/reflection-docblock <3.0||>=3.2.0,<3.2.2
phpdocumentor/type-resolver <0.2.1
phpunit/phpunit <4.8.35|<5.4.3,>=5.0

replaces
symfony/asset self.version
symfony/browser-kit self.version
symfony/cache self.version
symfony/class-loader self.version
symfony/config self.version
symfony/console self.version
symfony/css-selector self.version
symfony/debug self.version
symfony/debug-bundle self.version
symfony/dependency-injection self.version
symfony/doctrine-bridge self.version
symfony/dom-crawler self.version
symfony/dotenv self.version
symfony/event-dispatcher self.version
symfony/expression-language self.version
symfony/filesystem self.version
symfony/finder self.version
symfony/form self.version
symfony/framework-bundle self.version
symfony/http-foundation self.version
symfony/http-kernel self.version
symfony/inflector self.version
symfony/intl self.version
symfony/ldap self.version
symfony/monolog-bridge self.version
symfony/options-resolver self.version
symfony/process self.version
symfony/property-access self.version
symfony/property-info self.version
symfony/proxy-manager-bridge self.version
symfony/routing self.version
symfony/security self.version
symfony/security-bundle self.version
symfony/security-core self.version
symfony/security-csrf self.version
symfony/security-guard self.version
symfony/security-http self.version
symfony/serializer self.version
symfony/stopwatch self.version
symfony/templating self.version
symfony/translation self.version
symfony/twig-bridge self.version
symfony/twig-bundle self.version
symfony/validator self.version
symfony/var-dumper self.version
symfony/web-link self.version
symfony/web-profiler-bundle self.version
symfony/web-server-bundle self.version
symfony/workflow self.version
symfony/yaml self.version
```

**Comment by slince** [comment]
symfony的正常，应该是这个包对php版本识别的有问题，看下版本
composer show ocramius/proxy-manager

**Comment by gouchaoer** [comment]
```
php70 composer.phar show show ocramius/proxy-manager


  [UnexpectedValueException]
  Could not parse version constraint ocramius/proxy-manager: Invalid version string "ocramius/proxy-manager"


show [--all] [-i|--installed] [-p|--platform] [-a|--available] [-s|--self] [-N|--name-only] [-P|--path] [-t|--tree] [-l|--latest] [-o|--outdated] [-m|--minor-only] [-D|--direct] [--strict] [-f|--format FORMAT] [--] [<package>] [<version>]
```

**Comment by slince** [comment]
建议你删除vendor重新安装一次再看看。

**Comment by gouchaoer** [comment]
换php7.2了，requirements里面可以把gd，intl，xml这几个拓展检查加上

**Comment by slince** [comment]
gd和intl 在执行安装命令时有检查， 不过没写在composer.json里
